onEvent('recipes',event=>{
    //从一份沙子中能有50%概率筛出基岩，10%概率筛出红石，使用线筛网，筛沙时间20ticks，含水
    /*event.recipes.createsifterSifting([
//输出物品，左边为物品右边为概率
            Item.of('minecraft:bedrock').withChance(0.5),
            Item.of('minecraft:redstone').withChance(0.1)
        ], [
//输入物品，左边为物品，右边为对应筛网
            'minecraft:sand','createsifter:string_mesh'
//在后面加入.waterlogged()会变成含水配方，加入.processingTime(int time)就会规定筛物品所用的时间
        ]).waterlogged() .processingTime(20)
//若是输出物品变得不是有概率限制的，可以尝试在输出物品的withChance(figure)后面加上.toJson()*/
    event.remove({input:'#createsifter:meshes'})
    event.remove({output:'#createsifter:meshes'})
    event.shaped('createsifter:brass_mesh',[
        'BBB',
        'BAB',
        'BBB'
    ],{
        A:'exnihilosequentia:emerald_mesh',
        B:'create:brass_ingot'
    })
    event.remove({output:'createsifter:sifter'})
    event.shaped('createsifter:sifter',[
        'DCD',
        'ABA',
        'EEE'
    ],{
        A:'create:deployer',
        B:'create:millstone',
        C:'#exnihilosequentia:sieves',
        D:'stick',
        E:'cobblestone'
    })
        /*event.recipes.createsifterSifting([
    ],[,'createsifter:brass_mesh'])*/
    event.recipes.createsifterSifting([
        Item.of('exnihilosequentia:copper_pieces').withChance(0.85),
        Item.of('exnihilosequentia:copper_pieces').withChance(0.85),
        Item.of('exnihilosequentia:gold_pieces').withChance(0.85),
        Item.of('exnihilosequentia:gold_pieces').withChance(0.85),
        Item.of('exnihilosequentia:iron_pieces').withChance(0.85),
        Item.of('exnihilosequentia:iron_pieces').withChance(0.85),
        Item.of('exnihilosequentia:zinc_pieces').withChance(0.85),
        Item.of('exnihilosequentia:zinc_pieces').withChance(0.85),
    ],['gilded_blackstone','createsifter:brass_mesh'])
    event.recipes.createsifterSifting([
        Item.of('beetroot_seeds').withChance(0.55),
        Item.of('beetroot_seeds').withChance(0.75),
        Item.of('farmersdelight:tomato_seeds').withChance(0.55),
        Item.of('farmersdelight:tomato_seeds').withChance(0.75),
        Item.of('farmersdelight:cabbage_seeds').withChance(0.55),
        Item.of('farmersdelight:cabbage_seeds').withChance(0.75),
        Item.of('exnihilosequentia:zinc_pieces').withChance(0.85),
        Item.of('exnihilosequentia:zinc_pieces')
    ],['podzol','createsifter:brass_mesh'])
    event.recipes.createsifterSifting([
        Item.of('farmersdelight:rice_panicle').withChance(0.05),
        Item.of('exnihilosequentia:iron_pieces').withChance(0.6),
        Item.of('exnihilosequentia:iron_pieces').withChance(0.7),
        Item.of('exnihilosequentia:iron_pieces').withChance(0.8),
        Item.of('exnihilosequentia:copper_pieces').withChance(0.6),
        Item.of('exnihilosequentia:copper_pieces').withChance(0.7),
        Item.of('exnihilosequentia:copper_pieces').withChance(0.8),
    ],['cobbled_deepslate','createsifter:brass_mesh'])
    event.recipes.createsifterSifting([
        Item.of('dirt').withChance(0.6),
        Item.of('dirt').withChance(0.8),
        Item.of('dirt')
    ],['coarse_dirt','createsifter:brass_mesh'])
    event.recipes.createsifterSifting([
        Item.of('flint').withChance(0.65),
        Item.of('flint').withChance(0.75),
        Item.of('flint').withChance(0.85),
        Item.of('exnihilosequentia:iron_pieces').withChance(0.45),
        Item.of('exnihilosequentia:iron_pieces').withChance(0.55),
        Item.of('exnihilosequentia:iron_pieces').withChance(0.75),
    ],['gravel','createsifter:brass_mesh'])
    event.recipes.createsifterSifting([
        Item.of('wheat_seeds').withChance(0.45),
        Item.of('wheat_seeds').withChance(0.6),
        Item.of('exnihilosequentia:stone_pebble').withChance(0.45),
        Item.of('exnihilosequentia:stone_pebble').withChance(0.6),
        Item.of('exnihilosequentia:andesite_pebble').withChance(0.45),
        Item.of('exnihilosequentia:andesite_pebble').withChance(0.6),
    ],['dirt','createsifter:brass_mesh'])
    event.recipes.createsifterSifting([
        Item.of('exnihilosequentia:carrot_seeds').withChance(0.6),
        Item.of('exnihilosequentia:carrot_seeds').withChance(0.7),
        Item.of('pumpkin_seeds').withChance(0.6),
        Item.of('pumpkin_seeds').withChance(0.7),
        Item.of('exnihilosequentia:sugarcane_seeds').withChance(0.6),
        Item.of('exnihilosequentia:sugarcane_seeds').withChance(0.7),
        Item.of('exnihilosequentia:cactus_seeds').withChance(0.6),
        Item.of('exnihilosequentia:cactus_seeds').withChance(0.7),
        Item.of('farmersdelight:onion').withChance(0.6),
        Item.of('farmersdelight:onion').withChance(0.7),
        Item.of('melon_seeds').withChance(0.6),
        Item.of('melon_seeds').withChance(0.7),
        Item.of('exnihilosequentia:bamboo_seeds').withChance(0.6),
        Item.of('exnihilosequentia:bamboo_seeds').withChance(0.7),
    ],['dirt_path','createsifter:brass_mesh'])
    event.recipes.createsifterSifting([
        Item.of('sea_pickle').withChance(0.55),
        Item.of('kelp').withChance(0.55)
    ],['sand','createsifter:brass_mesh'])
    event.recipes.createsifterSifting([
        Item.of('sea_pickle').withChance(0.95),
        Item.of('kelp').withChance(0.95),
    ],['sand','createsifter:brass_mesh']).waterlogged()
})