onEvent('recipes',event=>{/*
    event.recipes.createFilling('spruce_sapling',['oak_sapling',Fluid.of('water',100)])
    event.recipes.createFilling('birch_sapling',['spruce_sapling',Fluid.of('water',100)])
    event.recipes.createFilling('jungle_sapling',['birch_sapling',Fluid.of('water',100)])
    event.recipes.createFilling('acacia_sapling',['jungle_sapling',Fluid.of('water',100)])
    event.recipes.createFilling('dark_oak_sapling',['acacia_sapling',Fluid.of('water',100)])
    event.recipes.createFilling('azalea',['dark_oak_sapling',Fluid.of('water',100)])
    event.recipes.createFilling('flowering_azalea',['azalea',Fluid.of('water',100)])
    event.recipes.createFilling('oak_sapling',['flowering_azalea',Fluid.of('water',100)])
*/
    event.shapeless('create:tree_fertilizer',['2x bone_meal',['tube_coral','bubble_coral','brain_coral','fire_coral','horn_coral'],['tube_coral','bubble_coral','brain_coral','fire_coral','horn_coral']])
    
    event.remove({output:'globe_banner_pattern'})
    event.remove({output:'skull_banner_pattern'})
    event.remove({output:'flower_banner_pattern'})
    event.remove({output:'mojang_banner_pattern'})
    event.remove({output:'piglin_banner_pattern'})
    event.remove({output:"creeper_banner_pattern"})

    event.shapeless('coal','charcoal')
    event.shapeless('charcoal','coal')

    event.recipes.createCompacting('coal_ore',['coal','stone'])
    event.recipes.createCompacting('iron_ore',['iron_ingot','stone'])
    event.recipes.createCompacting('copper_ore',['copper_ingot','stone'])
    event.recipes.createCompacting('gold_ore',['gold_ingot','stone'])
    event.recipes.createCompacting('redstone_ore',['redstone','stone'])
    event.recipes.createCompacting('emerald_ore',['emerald','stone'])
    event.recipes.createCompacting('lapis_ore',['lapis_lazuli','stone'])
    event.recipes.createCompacting('diamond_ore',['diamond','stone'])

    event.recipes.createCompacting('deepslate_coal_ore',['coal','deepslate'])
    event.recipes.createCompacting('deepslate_iron_ore',['iron_ingot','deepslate'])
    event.recipes.createCompacting('deepslate_copper_ore',['copper_ingot','deepslate'])
    event.recipes.createCompacting('deepslate_gold_ore',['gold_ingot','deepslate'])
    event.recipes.createCompacting('deepslate_redstone_ore',['redstone','deepslate'])
    event.recipes.createCompacting('deepslate_emerald_ore',['emerald','deepslate'])
    event.recipes.createCompacting('deepslate_lapis_ore',['lapis_lazuli','deepslate'])
    event.recipes.createCompacting('deepslate_diamond_ore',['diamond','deepslate'])

    event.recipes.createCompacting('nether_gold_ore',['gold_ingot','netherrack'])
    event.recipes.createCompacting('nether_quartz_ore',['quartz','netherrack'])

    event.smelting('calcite','diorite')
    event.shapeless('create:asurine',['cobblestone','blue_dye'])
    event.shapeless('create:crimsite',['cobblestone','red_dye'])
    event.shapeless('create:limestone',['stone','gray_dye'])
    event.shapeless('create:ochrum',['stone','yellow_dye'])
    event.shapeless('create:veridium',['cobblestone','green_dye'])
})
onEvent('lootjs',event=>{
    event.addBlockLootModifier('coal_ore').removeLoot('coal').addLoot('coal_ore')
    event.addBlockLootModifier('iron_ore').removeLoot('raw_iron').addLoot('iron_ore')
    event.addBlockLootModifier('copper_ore').removeLoot('raw_copper').addLoot('copper_ore')
    event.addBlockLootModifier('gold_ore').removeLoot('raw_gold').addLoot('gold_ore')
    event.addBlockLootModifier('redstone_ore').removeLoot('redstone').addLoot('redstone_ore')
    event.addBlockLootModifier('emerald_ore').removeLoot('emerald').addLoot('emerald_ore')
    event.addBlockLootModifier('lapis_ore').removeLoot('lapis_lazuli').addLoot('lapis_ore')
    event.addBlockLootModifier('diamond_ore').removeLoot('diamond').addLoot('diamond_ore')

    event.addBlockLootModifier('deepslate_coal_ore').removeLoot('coal').addLoot('deepslate_coal_ore')
    event.addBlockLootModifier('deepslate_iron_ore').removeLoot('raw_iron').addLoot('deepslate_iron_ore')
    event.addBlockLootModifier('deepslate_copper_ore').removeLoot('raw_copper').addLoot('deepslate_copper_ore')
    event.addBlockLootModifier('deepslate_gold_ore').removeLoot('raw_gold').addLoot('deepslate_gold_ore')
    event.addBlockLootModifier('deepslate_redstone_ore').removeLoot('redstone').addLoot('deepslate_redstone_ore')
    event.addBlockLootModifier('deepslate_emerald_ore').removeLoot('emerald').addLoot('deepslate_emerald_ore')
    event.addBlockLootModifier('deepslate_lapis_ore').removeLoot('lapis_lazuli').addLoot('deepslate_lapis_ore')
    event.addBlockLootModifier('deepslate_diamond_ore').removeLoot('diamond').addLoot('deepslate_diamond_ore')

    event.addBlockLootModifier('nether_gold_ore').removeLoot('gold_nugget').addLoot('nether_gold_ore')
    event.addBlockLootModifier('nether_quartz_ore').removeLoot('quartz').addLoot('nether_quartz_ore')
})