onEvent('recipes',event=>{
    event.recipes.createMixing('4x kubejs:fishfood',[Fluid.of('kubejs:protein',200),'create:wheat_flour']).heated()
    event.recipes.createMixing(Fluid.of("exnihilosequentia:sea_water",1000),[Fluid.of('minecraft:water',1000),'minecraft:kelp','minecraft:sea_pickle']).heated()
    event.recipes.createMixing(Fluid.of("exnihilosequentia:sea_water",1000),[Fluid.of('minecraft:water',1000),'minecraft:kelp','minecraft:seagrass']).heated()
    event.remove({type:'exnihilosequentia:fluid_transform'})
    //鱼
    event.remove({output:'minecraft:fishing_rod'})
    event.recipes.createMixing([
        Item.of('minecraft:salmon').withChance(0.7),
        Item.of('minecraft:kelp').withChance(0.4),
        Item.of('minecraft:sea_pickle').withChance(0.4),
        Item.of('minecraft:seagrass').withChance(0.4)
    ],[Fluid.of('minecraft:water',500),'kubejs:fishfood'])
    event.recipes.createMixing([
        Item.of('minecraft:cod').withChance(0.7),
        Item.of('minecraft:kelp').withChance(0.4),
        Item.of('minecraft:sea_pickle').withChance(0.4),
        Item.of('minecraft:seagrass').withChance(0.4)
    ],[Fluid.of('exnihilosequentia:sea_water',500),'kubejs:fishfood'])
    event.recipes.createMixing(Item.of('minecraft:pufferfish').withChance(0.6),[Fluid.of('minecraft:water',250),Fluid.of('exnihilosequentia:sea_water',250),'kubejs:fishfood'])
    event.recipes.createMixing(Item.of('minecraft:tropical_fish').withChance(0.3),[Fluid.of('exnihilosequentia:sea_water',500),'kubejs:fishfood']).heated()
    //珊瑚
    event.recipes.createMixing([
        Item.of('exnihilosequentia:blue_coral_larvae').withChance(0.4),
        Item.of('exnihilosequentia:purple_coral_larvae').withChance(0.4),
        Item.of('exnihilosequentia:red_coral_larvae').withChance(0.4),
        Item.of('exnihilosequentia:yellow_coral_larvae').withChance(0.4),
        Item.of('exnihilosequentia:pink_coral_larvae').withChance(0.4),
        Item.of('minecraft:tropical_fish').withChance(0.9)
    ],[Fluid.of('exnihilosequentia:sea_water',500),'minecraft:tropical_fish','minecraft:clay_ball'])
    event.remove({input:'exnihilosequentia:blue_coral_larvae'})
    event.remove({input:'exnihilosequentia:purple_coral_larvae'})
    event.remove({input:'exnihilosequentia:red_coral_larvae'})
    event.remove({input:'exnihilosequentia:yellow_coral_larvae'})
    event.remove({input:'exnihilosequentia:pink_coral_larvae'})
    event.recipes.createMixing([Item.of('minecraft:tropical_fish').withChance(0.8),'minecraft:tube_coral_block'],['exnihilosequentia:blue_coral_larvae',Fluid.of('exnihilosequentia:sea_water',500),'minecraft:tropical_fish','minecraft:clay'])
    event.recipes.createMixing([Item.of('minecraft:tropical_fish').withChance(0.8),'minecraft:brain_coral_block'],['exnihilosequentia:pink_coral_larvae',Fluid.of('exnihilosequentia:sea_water',500),'minecraft:tropical_fish','minecraft:clay'])
    event.recipes.createMixing([Item.of('minecraft:tropical_fish').withChance(0.8),'minecraft:bubble_coral_block'],['exnihilosequentia:purple_coral_larvae',Fluid.of('exnihilosequentia:sea_water',500),'minecraft:tropical_fish','minecraft:clay'])
    event.recipes.createMixing([Item.of('minecraft:tropical_fish').withChance(0.8),'minecraft:fire_coral_block'],['exnihilosequentia:red_coral_larvae',Fluid.of('exnihilosequentia:sea_water',500),'minecraft:tropical_fish','minecraft:clay'])
    event.recipes.createMixing([Item.of('minecraft:tropical_fish').withChance(0.8),'minecraft:horn_coral_block'],['exnihilosequentia:yellow_coral_larvae',Fluid.of('exnihilosequentia:sea_water',500),'minecraft:tropical_fish','minecraft:clay'])
    event.remove({input:'tube_coral_block',type:'exnihilosequentia:hammer'})
    event.remove({input:'brain_coral_block',type:'exnihilosequentia:hammer'})
    event.remove({input:'bubble_coral_block',type:'exnihilosequentia:hammer'})
    event.remove({input:'fire_coral_block',type:'exnihilosequentia:hammer'})
    event.remove({input:'horn_coral_block',type:'exnihilosequentia:hammer'})
    event.recipes.createCrushing('4x minecraft:tube_coral','minecraft:tube_coral_block')
    event.recipes.createCrushing('4x minecraft:brain_coral','minecraft:brain_coral_block')
    event.recipes.createCrushing('4x minecraft:bubble_coral','minecraft:bubble_coral_block')
    event.recipes.createCrushing('4x minecraft:fire_coral','minecraft:fire_coral_block')
    event.recipes.createCrushing('4x minecraft:horn_coral','minecraft:horn_coral_block')
    event.recipes.createCompacting([Item.of('pufferfish').withChance(0.9),'brain_coral_block'],['pufferfish',['tube_coral_block','bubble_coral_block','fire_coral_block','horn_coral_block']])
    /*
    event.recipes.createCompacting([Item.of('exnihilosequentia:pink_coral_larvae').withChance(0.4)],'tube_coral_block',)
    event.recipes.createCompacting([Item.of('exnihilosequentia:pink_coral_larvae').withChance(0.4)],'bubble_coral_block',)
    event.recipes.createCompacting([Item.of('exnihilosequentia:pink_coral_larvae').withChance(0.4)],'fire_coral_block',)
    event.recipes.createCompacting([Item.of('exnihilosequentia:pink_coral_larvae').withChance(0.4)],'horn_coral_block',)
    event.recipes.createCompacting([Item.of('brain_coral_block').withChance(0.8)],'4x tube_coral',)
    event.recipes.createCompacting([Item.of('brain_coral_block').withChance(0.8)],'4x bubble_coral',)
    event.recipes.createCompacting([Item.of('brain_coral_block').withChance(0.8)],'4x fire_coral',)
    event.recipes.createCompacting([Item.of('brain_coral_block').withChance(0.8)],'4x horn_coral',)*/
    //🍣
    event.remove({output:'bowl'})
    event.recipes.createCutting(['minecraft:bowl',Item.of('minecraft:bowl').withChance(0.4)],'#minecraft:planks')
    event.remove({output:'farmersdelight:kelp_roll'})
    event.recipes.createSequencedAssembly('farmersdelight:kelp_roll','minecraft:dried_kelp',[
        event.recipes.createPressing('kubejs:incomplete_sushi','kubejs:incomplete_sushi'),
        event.recipes.createDeploying('kubejs:incomplete_sushi',['kubejs:incomplete_sushi','farmersdelight:cooked_rice']),
        event.recipes.createDeploying('kubejs:incomplete_sushi',['kubejs:incomplete_sushi','farmersdelight:cooked_salmon_slice']),
        event.recipes.createDeploying('kubejs:incomplete_sushi',['kubejs:incomplete_sushi','farmersdelight:cooked_cod_slice']),
        event.recipes.createDeploying('kubejs:incomplete_sushi',['kubejs:incomplete_sushi','farmersdelight:cooked_bacon']),
        event.recipes.createPressing('kubejs:incomplete_sushi','kubejs:incomplete_sushi')
    ])
    .transitionalItem('kubejs:incomplete_sushi')
    .loops(1)
    //woc,冰
    event.recipes.createCompacting([Item.of('minecraft:pufferfish').withChance(0.95),'minecraft:ice'],[Fluid.of('minecraft:water',1000),'minecraft:pufferfish'])
    //僵尸头
    event.recipes.createCompacting('minecraft:zombie_head',[Fluid.of('kubejs:protein',500),'minecraft:packed_ice','minecraft:brain_coral_block']).heated()
    event.recipes.createSequencedAssembly('kubejs:stupid_zombie','minecraft:zombie_head',[
        event.recipes.createCutting('kubejs:incomplete_stupid_zombie','kubejs:incomplete_stupid_zombie'),
        event.recipes.createDeploying('kubejs:incomplete_stupid_zombie',['kubejs:incomplete_stupid_zombie','create:cogwheel']),
        event.recipes.createDeploying('kubejs:incomplete_stupid_zombie',['kubejs:incomplete_stupid_zombie','create:large_cogwheel']),
        event.recipes.createPressing('kubejs:incomplete_stupid_zombie','kubejs:incomplete_stupid_zombie')
    ])
    .transitionalItem('kubejs:incomplete_stupid_zombie')
    .loops(1)
    event.recipes.createSequencedAssembly('kubejs:smart_zombie','kubejs:stupid_zombie',[
        event.recipes.createPressing('kubejs:incomplete_smart_zombie','kubejs:incomplete_smart_zombie'),
        event.recipes.createFilling('kubejs:incomplete_smart_zombie',['kubejs:incomplete_smart_zombie',Fluid.of('milk',500)]),
        event.recipes.createDeploying('kubejs:incomplete_smart_zombie',['kubejs:incomplete_smart_zombie','farmersdelight:fried_egg']),
        event.recipes.createDeploying('kubejs:incomplete_smart_zombie',['kubejs:incomplete_smart_zombie','farmersdelight:fried_rice']),
        event.recipes.createDeploying('kubejs:incomplete_smart_zombie',['kubejs:incomplete_smart_zombie','farmersdelight:hamburger'])
    ])
    .transitionalItem('kubejs:incomplete_smart_zombie')
    .loops(1)
    event.remove({output:'create:electron_tube'})
    event.shaped('create:electron_tube',[
        ' A ',
        ' B ',
        ' C '
    ],{
        A:'create:polished_rose_quartz',
        B:'kubejs:stupid_zombie',
        C:'create:iron_sheet'
    })
    event.remove({output:'create:mechanical_crafter'})
    event.recipes.createCompacting('create:mechanical_crafter',['create:brass_casing','kubejs:smart_zombie','minecraft:crafting_table'])
    event.recipes.createSequencedAssembly([
        Item.of('create:precision_mechanism').withChance(0.9),
        Item.of('kubejs:stupid_zombie').withChance(0.05),
        Item.of('kubejs:smart_zombie').withChance(0.05)
    ],'create:brass_sheet',[
        event.recipes.createPressing('create:incomplete_precision_mechanism','create:incomplete_precision_mechanism'),
        event.recipes.createDeploying('create:incomplete_precision_mechanism',['create:incomplete_precision_mechanism','create:cogwheel']),
        event.recipes.createDeploying('create:incomplete_precision_mechanism',['create:incomplete_precision_mechanism','create:large_cogwheel']),
        event.recipes.createDeploying('create:incomplete_precision_mechanism',['create:incomplete_precision_mechanism','kubejs:smart_zombie']),
        event.recipes.createDeploying('create:incomplete_precision_mechanism',['create:incomplete_precision_mechanism','create:cogwheel']),
        event.recipes.createDeploying('create:incomplete_precision_mechanism',['create:incomplete_precision_mechanism','create:large_cogwheel']),
    ])
    .transitionalItem('create:incomplete_precision_mechanism')
    .loops(1)
    event.remove({output:'create:mechanical_arm'})
    event.recipes.createMechanicalCrafting('create:mechanical_arm',[
        ' FAF ',
        ' B A ',
        '   C ',
        'DDDED'
    ],{
        A:'create:shaft',
        B:'create:brass_hand',
        C:'kubejs:stupid_zombie',
        D:'create:brass_sheet',
        E:'create:precision_mechanism',
        F:'create:andesite_alloy'
    })
    event.recipes.createMechanicalCrafting('create:mechanical_arm',[
        'BCF',
        'EDE'
    ],{
        B:'create:brass_hand',
        C:'kubejs:smart_zombie',
        D:'create:precision_mechanism',
        E:'create:brass_sheet',
        F:'create:bar_of_chocolate'
    })
    //粉碎轮
    event.remove({output:'minecraft:packed_ice'})
    event.recipes.createSplashing('minecraft:packed_ice','minecraft:ice')
    event.recipes.createCrushing([
        Item.of('3x kubejs:ice_cube').withChance(0.85),
        Item.of('minecraft:packed_ice').withChance(0.1),
        Item.of('minecraft:ice').withChance(0.05)
    ],'blue_ice')
    event.remove({output:'farmersdelight:rice_roll_medley_block'})
    event.recipes.createMechanicalCrafting('kubejs:expensive_sushi',[
        'MMFFFFFMM',
        'EIIIEHHHE',
        'EJJJJJJJE',
        'JAAAAAAAJ',
        'AFFNANFFA',
        'KKKOAOLLL',
        'CCCBABDDD',
        'BBBAAABBB',
        'AAAAGAAAA',
    ],{
        A:'kubejs:ice_cube',
        B:'farmersdelight:canvas',
        C:'farmersdelight:cod_slice',
        D:'farmersdelight:salmon_slice',
        E:'farmersdelight:kelp_roll_slice',
        F:'minecraft:brain_coral',
        G:'minecraft:bowl',
        H:'farmersdelight:salmon_roll',
        I:'farmersdelight:cod_roll',
        J:'minecraft:dried_kelp',
        K:'farmersdelight:cooked_cod_slice',
        L:'farmersdelight:cooked_salmon_slice',
        M:'minecraft:seagrass',
        N:'minecraft:sea_pickle',
        O:'minecraft:kelp'
    })
    event.recipes.createMechanicalCrafting('farmersdelight:rice_roll_medley_block',[
        'BAAAB',
        'EDDDE',
        'CFGFC'
    ],{
        A:'farmersdelight:salmon_roll',
        B:'minecraft:brain_coral',
        C:'minecraft:seagrass',
        D:'farmersdelight:kelp_roll_slice',
        E:'farmersdelight:cod_roll',
        F:'kubejs:ice_cube',
        G:'minecraft:bowl'
    })
    //event.shapeless('farmersdelight:rice_roll_medley_block','kubejs:expensive_sushi')
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:smart_zombie').withChance(0.6),
        Item.of('kubejs:stupid_zombie').withChance(0.3),
        Item.of('minecraft:zombie_head').withChance(0.1),
    ],'kubejs:stupid_zombie',[
        event.recipes.createDeploying('kubejs:incomplete_stupid_zombie',['kubejs:incomplete_stupid_zombie','kubejs:expensive_sushi']).keepHeldItem(),
        event.recipes.createPressing('kubejs:incomplete_stupid_zombie','kubejs:incomplete_stupid_zombie')
    ])
    .transitionalItem('kubejs:incomplete_stupid_zombie')
    .loops(1)
    //挖矿
    event.recipes.createDeploying([
        Item.of('minecraft:diamond').withChance(0.01),
        Item.of('minecraft:gold_ingot').withChance(0.1),
        Item.of('minecraft:copper_ingot').withChance(0.3),
        Item.of('minecraft:iron_ingot').withChance(0.4),
        Item.of('create:zinc_ingot').withChance(0.2),
        Item.of('kubejs:smart_zombie').withChance(0.95)
    ],['kubejs:smart_zombie',Item.of('minecraft:iron_pickaxe').ignoreNBT()])
    .damageIngredient(Item.of('minecraft:iron_pickaxe').ignoreNBT())
    event.recipes.createDeploying([
        Item.of('minecraft:netherite_scrap').withChance(0.01),
        Item.of('minecraft:diamond').withChance(0.05),
        Item.of('minecraft:gold_ingot').withChance(0.15),
        Item.of('minecraft:copper_ingot').withChance(0.45),
        Item.of('minecraft:iron_ingot').withChance(0.5),
        Item.of('create:zinc_ingot').withChance(0.35),
        Item.of('kubejs:smart_zombie').withChance(0.9)
    ],['kubejs:smart_zombie',Item.of('minecraft:diamond_pickaxe').ignoreNBT()])
    .damageIngredient(Item.of('minecraft:diamond_pickaxe').ignoreNBT())
    event.recipes.createDeploying([
        Item.of('minecraft:netherite_scrap').withChance(0.05),
        Item.of('minecraft:netherite_ingot').withChance(0.005),
        Item.of('minecraft:diamond').withChance(0.1),
        Item.of('minecraft:gold_ingot').withChance(0.2),
        Item.of('minecraft:copper_ingot').withChance(0.5),
        Item.of('minecraft:iron_ingot').withChance(0.75),
        Item.of('create:zinc_ingot').withChance(0.5),
        Item.of('kubejs:smart_zombie').withChance(0.8)
    ],['kubejs:smart_zombie',Item.of('minecraft:netherite_pickaxe').ignoreNBT()])
    .damageIngredient(Item.of('minecraft:netherite_pickaxe').ignoreNBT())
})

