onEvent('recipes',event=>{
    event.remove({output:'cake'}) 
    event.recipes.createMixing([Fluid.of('kubejs:fluid6',500)],[
        '10x create:wheat_flour','3x sugar','5x egg',Fluid.of('milk',400)
    ])
    //整形
    event.recipes.createCompacting([
        Item.of('kubejs:step1').withChance(0.95),
        Item.of('kubejs:item1-1').withChance(0.1),
        Item.of('kubejs:item1-2').withChance(0.6),
        Item.of('kubejs:item1-2').withChance(0.4)
    ],Fluid.of('kubejs:fluid6',500)).heated()
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step2').withChance(90),
        Item.of('kubejs:fail1').withChance(5),
        Item.of('16x kubejs:item1-2').withChance(3),
        Item.of('12x kubejs:item1-2').withChance(1),
        Item.of('8x kubejs:item1-2').withChance(1)
    ],'kubejs:step1',[
        event.recipes.createCutting('kubejs:proc1','kubejs:proc1'),
        event.recipes.createDeploying('kubejs:proc1',['kubejs:proc1',Item.of('kubejs:cake_knife').ignoreNBT()])
    ]).transitionalItem('kubejs:proc1').loops(2)
    event.recipes.createSequencedAssembly([
        Item.of('3x kubejs:step3-1').withChance(90),
        Item.of('2x kubejs:step3-1').withChance(5),
        Item.of('kubejs:step3-1').withChance(3),
        Item.of('16x kubejs:item1-1').withChance(2)
    ],'kubejs:step2',[
        event.recipes.createDeploying('kubejs:proc2',['kubejs:proc2',Item.of('kubejs:cake_knife').ignoreNBT()])
    ]).transitionalItem('kubejs:proc2').loops(3)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step3-2').withChance(0.8),
        Item.of('4x kubejs:item1-1').withChance(0.1),
        Item.of('kubejs:fail2').withChance(0.1)
    ],'kubejs:step3-1',[
        event.recipes.createDeploying('kubejs:proc3-1',['kubejs:proc3-1',Item.of('kubejs:cake_knife').ignoreNBT()])
    ]).transitionalItem('kubejs:proc3-1').loops(1)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step4').withChance(75),
        Item.of('3x kubejs:fail2').withChance(10),
        Item.of('kubejs:fail1').withChance(15)
    ],'kubejs:step3-1',[
        event.recipes.createFilling('kubejs:proc3-1',['kubejs:proc3-1',Fluid.of('kubejs:fluid1',200)]),
        event.recipes.createDeploying('kubejs:proc3-1',['kubejs:proc3-1',Item.of(Item.of('kubejs:cake_shovel').ignoreNBT()).ignoreNBT()]),
        event.recipes.createDeploying('kubejs:proc3-1',['kubejs:proc3-1','kubejs:step3-2'])
    ]).transitionalItem('kubejs:proc3-1').loops(2)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step5').withChance(7),
        Item.of('kubejs:fail2').withChance(3)
    ],'kubejs:step4',[
        event.recipes.createFilling('kubejs:proc4',['kubejs:proc4',Fluid.of('kubejs:fluid1',100)]),
        event.recipes.createDeploying('kubejs:proc4',['kubejs:proc4','kubejs:item2']),
        event.recipes.createDeploying('kubejs:proc4',['kubejs:proc4','kubejs:item3']),
        event.recipes.createFilling('kubejs:proc4',['kubejs:proc4',Fluid.of('create:chocolate',100)]),
    ]).transitionalItem('kubejs:proc4').loops(3)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step6').withChance(7),
        Item.of('kubejs:fail1').withChance(3)
    ],'kubejs:step5',[
        event.recipes.createFilling('kubejs:proc5',['kubejs:proc5',Fluid.of('kubejs:fluid1',200)]),
        event.recipes.createDeploying('kubejs:proc5',['kubejs:proc5',Item.of('kubejs:cake_shovel').ignoreNBT()]),
        event.recipes.createDeploying('kubejs:proc5',['kubejs:proc5','kubejs:step3-1'])
    ]).transitionalItem('kubejs:proc5').loops(1)
    //裱花
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step7').withChance(65),
        Item.of('kubejs:fail1').withChance(10),
        Item.of('kubejs:fail3').withChance(25)
    ],'kubejs:step6',[
        event.recipes.createFilling('kubejs:proc6',['kubejs:proc6',Fluid.of('kubejs:fluid1',400)]),
        event.recipes.createDeploying('kubejs:proc6',['kubejs:proc6',Item.of('kubejs:cake_shovel').ignoreNBT()]),
        event.recipes.createPressing('kubejs:proc6','kubejs:proc6'),
        event.recipes.createDeploying('kubejs:proc6',['kubejs:proc6',Item.of('kubejs:cake_shovel').ignoreNBT()])
    ]).transitionalItem('kubejs:proc6').loops(4)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step8-1').withChance(65),
        Item.of('kubejs:fail3').withChance(35)
    ],'kubejs:step7',[
        event.recipes.createFilling('kubejs:proc7',['kubejs:proc7',Fluid.of('kubejs:fluid3',300)]),
        event.recipes.createDeploying('kubejs:proc7',['kubejs:proc7',Item.of('kubejs:cake_shovel').ignoreNBT()]),
        event.recipes.createFilling('kubejs:proc7',['kubejs:proc7',Fluid.of('kubejs:fluid2',100)]),
        event.recipes.createDeploying('kubejs:proc7',['kubejs:proc7',Item.of('kubejs:cake_shovel').ignoreNBT()])
    ]).transitionalItem('kubejs:proc7').loops(4)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step8-2').withChance(6),
        Item.of('kubejs:fail3').withChance(4)
    ],'kubejs:step8-1',[
        event.recipes.createFilling('kubejs:proc8-1',['kubejs:proc8-1',Fluid.of('kubejs:fluid5',200)]),
        event.recipes.createDeploying('kubejs:proc8-1',['kubejs:proc8-1',Item.of('kubejs:cake_shovel').ignoreNBT()]),
        event.recipes.createFilling('kubejs:proc8-1',['kubejs:proc8-1',Fluid.of('kubejs:fluid1',200)]),
        event.recipes.createDeploying('kubejs:proc8-1',['kubejs:proc8-1',Item.of('kubejs:cake_shovel').ignoreNBT()])
    ]).transitionalItem('kubejs:proc8-1').loops(4)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step8-3').withChance(6),
        Item.of('kubejs:fail3').withChance(4)
    ],'kubejs:step8-2',[
        event.recipes.createFilling('kubejs:proc8-2',['kubejs:proc8-2',Fluid.of('kubejs:fluid3',200)]),
        event.recipes.createDeploying('kubejs:proc8-2',['kubejs:proc8-2',Item.of('kubejs:cake_shovel').ignoreNBT()]),
        event.recipes.createFilling('kubejs:proc8-2',['kubejs:proc8-2',Fluid.of('kubejs:fluid1',200)]),
        event.recipes.createDeploying('kubejs:proc8-2',['kubejs:proc8-2',Item.of('kubejs:cake_shovel').ignoreNBT()])
    ]).transitionalItem('kubejs:proc8-2').loops(4)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step9').withChance(6),
        Item.of('kubejs:fail3').withChance(4)
    ],'kubejs:step8-3',[
        event.recipes.createFilling('kubejs:proc8-3',['kubejs:proc8-3',Fluid.of('kubejs:fluid5',200)]),
        event.recipes.createDeploying('kubejs:proc8-3',['kubejs:proc8-3',Item.of('kubejs:cake_shovel').ignoreNBT()]),
        event.recipes.createFilling('kubejs:proc8-3',['kubejs:proc8-3',Fluid.of('kubejs:fluid4',200)]),
        event.recipes.createDeploying('kubejs:proc8-3',['kubejs:proc8-3',Item.of('kubejs:cake_shovel').ignoreNBT()])
    ]).transitionalItem('kubejs:proc8-3').loops(4)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step10').withChance(55),
        Item.of('kubejs:fail3').withChance(35),
        Item.of('kubejs:step8-3').withChance(10)
    ],'kubejs:step9',[
        event.recipes.createFilling('kubejs:proc9',['kubejs:proc9',Fluid.of('create:chocolate',1000)]),
        event.recipes.createDeploying('kubejs:proc9',['kubejs:proc9',Item.of('kubejs:cake_shovel').ignoreNBT()]),
    ]).transitionalItem('kubejs:proc8-3').loops(2)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step11').withChance(55),
        Item.of('kubejs:step10').withChance(35),
        Item.of('kubejs:fail3').withChance(10)
    ],'kubejs:step10',[
        event.recipes.createFilling('kubejs:proc10',['kubejs:proc10',Fluid.of('kubejs:fluid1',1000)]),
        event.recipes.createFilling('kubejs:proc10',['kubejs:proc10',Fluid.of('kubejs:fluid3',800)]),
        event.recipes.createFilling('kubejs:proc10',['kubejs:proc10',Fluid.of('kubejs:fluid5',700)]),
        event.recipes.createFilling('kubejs:proc10',['kubejs:proc10',Fluid.of('kubejs:fluid4',600)]),
        event.recipes.createFilling('kubejs:proc10',['kubejs:proc10',Fluid.of('kubejs:fluid2',600)]),
        event.recipes.createDeploying('kubejs:proc10',['kubejs:proc10','kubejs:item3']),
    ]).transitionalItem('kubejs:proc10').loops(2)
    event.recipes.createSequencedAssembly([
        Item.of('cake').withChance(5),
        Item.of('kubejs:step11').withChance(3),
        Item.of('kubejs:step10').withChance(1),
        Item.of('kubejs:fail3').withChance(1)
    ],'kubejs:step11',[
        event.recipes.createDeploying('kubejs:proc11',['kubejs:proc11','glow_berries']),
        event.recipes.createDeploying('kubejs:proc11',['kubejs:proc11','create:chocolate_glazed_berries']),
        event.recipes.createDeploying('kubejs:proc11',['kubejs:proc11','kubejs:item2']),
        event.recipes.createDeploying('kubejs:proc11',['kubejs:proc11','sugar']),
    ]).transitionalItem('kubejs:proc11').loops(4)
    //原料生产
    event.recipes.createMixing(Fluid.of('kubejs:fluid1',250),[
        Fluid.of('milk',250),
        'sugar',
        Fluid.of('kubejs:oil',100)
    ])
    event.recipes.createMixing(Fluid.of('kubejs:fluid2',1000),[
        Fluid.of('kubejs:fluid1',1000),
        'cooked_porkchop','cooked_beef','cooked_chicken',
        'cooked_mutton','cooked_cod','cooked_salmon'
    ])
    event.recipes.createMixing(Fluid.of('kubejs:fluid3',1000),[
        Fluid.of('kubejs:fluid1',1000),
        'iron_ingot','copper_ingot','gold_ingot',
        'create:andesite_alloy','create:zinc_ingot','diamond'
    ])
    event.recipes.createMixing(Fluid.of('kubejs:fluid4',1000),[
        Fluid.of('kubejs:fluid1',1000),
        'tube_coral','brain_coral','bubble_coral',
        'fire_coral','horn_coral','pufferfish'
    ])
    event.recipes.createMixing(Fluid.of('kubejs:fluid5',1000),[
        Fluid.of('kubejs:fluid1',1000),
        'farmersdelight:tomato','carrot','farmersdelight:rice',
        'potato','farmersdelight:onion','farmersdelight:cabbage_leaf'
    ])
    event.recipes.createDeploying([
        Item.of('kubejs:item2').withChance(0.9),
        Item.of('kubejs:item2').withChance(0.85),
        Item.of('kubejs:item2').withChance(0.8),
        Item.of('kubejs:item2').withChance(0.75)
    ],['create:bar_of_chocolate',Item.of('kubejs:cake_knife').ignoreNBT()])
    event.recipes.createMixing(Item.of('kubejs:item3').withChance(0.8),[
        Fluid.of('milk',300),
        Fluid.of('kubejs:fluid1',100),
        '3x kubejs:ice_cube'
    ])
    //废物回收
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step1').withChance(3),
        Item.of('kubejs:fail1').withChance(6),
        Item.of('4x create:sweet_roll').withChance(1)
    ],'kubejs:item1-1',[
        event.recipes.createDeploying('kubejs:procitem1-1',['kubejs:procitem1-1','kubejs:item1-1']),
        event.recipes.createDeploying('kubejs:procitem1-1',['kubejs:procitem1-1','kubejs:item1-1']),
        event.recipes.createDeploying('kubejs:procitem1-1',['kubejs:procitem1-1','kubejs:item1-1']),
        event.recipes.createFilling('kubejs:procitem1-1',['4x kubejs:procitem1-1',Fluid.of('kubejs:fluid1',100)]),
        event.recipes.createPressing('kubejs:procitem1-1','kubejs:procitem1-1')
    ]).transitionalItem('kubejs:procitem1-1').loops(1)
    event.recipes.createCompacting([
        Item.of('kubejs:item1-1').withChance(0.7),
        Item.of('create:sweet_roll').withChance(0.1)
    ],['4x kubejs:item1-2',Fluid.of('kubejs:fluid1',50)])
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step1').withChance(0.75),
        Item.of('4x kubejs:item1-1').withChance(0.25)
    ],'kubejs:fail1',[
        event.recipes.createDeploying('kubejs:procfail1',['kubejs:procfail1',Item.of('kubejs:cake_knife').ignoreNBT()]),
        event.recipes.createPressing('kubejs:procfail1','kubejs:procfail1')
    ]).transitionalItem('kubejs:procfail1').loops(2)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step3-1').withChance(0.5),
        Item.of('kubejs:step3-2').withChance(0.2),
        Item.of('kubejs:item1-1').withChance(0.2),
        Item.of('4x kubejs:item1-2').withChance(0.1)
    ],'kubejs:fail2',[
        event.recipes.createDeploying('kubejs:procfail2',['kubejs:procfail2',Item.of('kubejs:cake_shovel').ignoreNBT()]),
        event.recipes.createPressing('kubejs:procfail2','kubejs:procfail2')
    ]).transitionalItem('kubejs:procfail2').loops(1)
    event.recipes.createSequencedAssembly([
        Item.of('kubejs:step7').withChance(0.9),
        Item.of('kubejs:fail1').withChance(0.1)
    ],'kubejs:fail3',[
        event.recipes.createDeploying('kubejs:procfail3',['kubejs:procfail3',Item.of('kubejs:cake_shovel').ignoreNBT()]),
        event.recipes.createFilling('kubejs:procfail3',['kubejs:procfail3',Fluid.of('kubejs:fluid1',1000)]),
        event.recipes.createDeploying('kubejs:procfail3',['kubejs:procfail3',Item.of('kubejs:cake_shovel').ignoreNBT()])
    ]).transitionalItem('kubejs:procfail3').loops(1)
})